import Head from "next/head";
import EventCard from "@/components/EventCard";

export default function Home({ events }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="Events app" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-between my-32 h-96">
        <h1 className="text-7xl font-bold w-1/2 self-center">
          City Beats: <br/> Dive into a World of Unmissable Events!
        </h1>
        <div className=" w-1/2 relative">
          <img className="w-96 h-96 rounded-full z-10 absolute right-36 -top-0" src="https://picsum.photos/200"  alt="lake" />
          <span className="w-96 h-96 inline-block rounded-full bg-green-600 absolute right-0 top-0"></span>
        </div>
      </div>
      <main className="flex flex-col gap-9 ">
        {events?.map((event) => (
          <EventCard
            key={event.id}
            url={`/events/${event.id}`}
            title={event.title}
            description={event.description}
            imageSrc={event.image}
          />
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("@/data/data.json");

  return {
    props: {
      events: events_categories || [],
    },
  };
}
