import Head from "next/head";
import styles from "@/styles/Home.module.css";
import EventCard from "@/components/EventCard";

export default function Home({ events }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold text-sky-600">
        Hello world!
      </h1>
      <h2 className="text-xl text-my-purple-color-333">
        Hello world!
      </h2>
      <main className={`${styles.main}`}>
        {events?.map((event) => (
          <EventCard
            key={event.id}
            url={`/events/${event.id}`}
            title={event.title}
            description={event.description}
            imageSrc={event.image}
          />
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("@/data/data.json");

  return {
    props: {
      events: events_categories || [],
    },
  };
}
